<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKmNxGe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKmNxGe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKmNxGe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKmNxGe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMKmNxGe\App_KernelDevDebugContainer([
    'container.build_hash' => 'MKmNxGe',
    'container.build_id' => '8f3afae1',
    'container.build_time' => 1601468908,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKmNxGe');
